networks:
  sensorshandler:
    driver: bridge


volumes:
  db_postgres:
    driver: local


services:
  postgres:
    image: 'postgres:15.1-alpine'
    container_name: sensors_grpc_postgres
    networks:
      - sensorshandler
    env_file:
      - .env
    ports:
      - '5439:5432'
    volumes:
      - db_postgres:/var/lib/postgresql/data