networks:
  sensorshandler:
    driver: bridge


volumes:
  db_postgres:
    driver: local
  data_redis:
    driver: local


services:
  postgres:
    image: 'postgres:15.1-alpine'
    container_name: sensors_grpc_postgres
    networks:
      - sensorshandler
    env_file:
      - .env
    ports:
      - '5439:5432'
    volumes:
      - db_postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    networks:
      - sensorshandler
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - data_redis:/data